# Generated by Django 6.1.1 on 2026-10-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_correct_immediately',
            field=models.BooleanField(default=True, verbose_name='Показувати правильну відповідь одразу'),
        ),
    ]
