# Generated by Django 6.1.1 on 2026-10-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_show_correct_immediately'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публічний квіз'),
        ),
    ]
